[EDMMGER]
description = "Gera"
volumes = ["EDMMGER_195_245", "EDMMGER_245_285", "EDMMGER_285_315"]
position_priority = [[{ id = "GER" }], [{ id = "HAL" }], [{ id = "MEI" }], [{ id = "HOF" }]]
runway_filter = [[]]

[EDMMHAL]
description = "Halle"
volumes = ["EDMMHAL_245_285", "EDMMHAL_195_245", "EDMMHAL_285_315"]
position_priority = [[{ id = "HAL" }], [{ id = "GER" }], [{ id = "MEI" }], [{ id = "HOF" }]]
runway_filter = [[]]

[EDMMMEI]
description = "Meißen"
volumes = ["EDMMMEI_165_245", "EDMMMEI_245_285", "EDMMMEI_285_315"]
position_priority = [[{ id = "MEI" }], [{ id = "GER" }], [{ id = "HAL" }], [{ id = "HOF" }]]
runway_filter = [[]]

[EDMMTRN]
description = "Thüringen Low Nord"
volumes = ["EDMMTRN_000_145", "EDMMTRN_055_145", "EDMMTRN_145_165", "EDMMTRN_165_195"]
position_priority = [
  [
    { id = "TRN" },
  ],
  [
    { id = "TRS" },
  ],
  [
    { id = "GER" },
  ],
  [
    { id = "MEI" },
  ],
  [
    { id = "HAL" },
  ],
  [
    { id = "HOF" },
  ],
]
runway_filter = [[]]

[EDMMTRS]
description = "Thüringen Low Süd"
volumes = ["EDMMTRS_000_145", "EDMMTRS_145_195"]
position_priority = [
  [
    { id = "TRS" },
  ],
  [
    { id = "TRN" },
  ],
  [
    { id = "GER" },
  ],
  [
    { id = "MEI" },
  ],
  [
    { id = "HAL" },
  ],
  [
    { id = "HOF" },
  ],
]
runway_filter = [[]]

[EDMMSAS]
description = "Sachsen Low"
volumes = ["EDMMSAS_000_165"]
position_priority = [
  [
    { id = "SAS" },
  ],
  [
    { id = "MEI" },
  ],
  [
    { id = "TRS" },
  ],
  [
    { id = "GER" },
  ],
  [
    { id = "HAL" },
  ],
  [
    { id = "HOF" },
  ],
]
runway_filter = [[]]

[EDMMBBG]
description = "Bamberg"
volumes = ["EDMMBBG_295_315", "EDMMBBG_245_295", "EDMMBBG_195_245"]
position_priority = [[{ id = "BBG" }], [{ id = "HOF" }], [{ id = "RDG" }]]
runway_filter = [[]]

[EDMMHOF]
description = "Hof"
volumes = ["EDMMHOF_195_245", "EDMMHOF_245_315"]
position_priority = [[{ id = "HOF" }], [{ id = "BBG" }], [{ id = "RDG" }]]
runway_filter = [[]]

[EDMMFRK]
description = "Franken Low"
volumes = ["EDMMFRK_135_195", "EDMMFRK_000_135"]
position_priority = [[{ id = "FRK" }], [{ id = "BBG" }], [{ id = "HOF" }], [{ id = "RDG" }]]
runway_filter = [[]]

[EDMMALB]
description = "Allersberg"
volumes = ["EDMMALB_105_135", "EDMMALB_245_315", "EDMMALB_135_245"]
position_priority = [[{ id = "ALB" }], [{ id = "WLD" }], [{ id = "RDG" }], [{ id = "EGG" }], [{ id = "ZUG" }]]
runway_filter = [[]]

[EDMMALB3]
description = "Allersberg (Ansbach Area)"
volumes = ["EDMMALB_245_305"]
position_priority = [
  [{ id = "ALB" }],
  [{ id = "WLD" }],
  [{ id = "RDG" }],
  [{ id = "EGG" }],
  [{ id = "ZUG" }],
  # TODO EDGG
  # [
  #   { fir = "EDGG", id = "WUR" },
  # ],
  # [
  #   { fir = "EDGG", id = "SLN" },
  # ],
  # [
  #   { fir = "EDGG", id = "DKB" },
  # ],
  # [
  #   { fir = "EDGG", id = "KTG" },
  # ],
  # [
  #   { fir = "EDGG", id = "BAD" },
  # ],
]
runway_filter = [[]]

[EDMMRDG]
description = "Roding"
volumes = ["EDMMRDG_000_135", "EDMMRDG_135_245", "EDMMRDG_245_315"]
position_priority = [[{ id = "RDG" }], [{ id = "EGG" }], [{ id = "ALB" }], [{ id = "WLD" }], [{ id = "ZUG" }]]
runway_filter = [[]]

[EDMMEGG]
description = "Eggenfelden"
volumes = ["EDMMEGG_000_195", "EDMMEGG_195_245", "EDMMEGG_245_315"]
position_priority = [[{ id = "EGG" }], [{ id = "RDG" }], [{ id = "ALB" }], [{ id = "WLD" }], [{ id = "ZUG" }]]
runway_filter = [[]]

[EDMMNDG]
description = "Nördlingen"
volumes = ["EDMMNDG_245_315", "EDMMNDG_195_245", "EDMMNDG_145_195", "EDMMNDG_105_145"]
position_priority = [[{ id = "NDG" }], [{ id = "TRU" }], [{ id = "WLD" }], [{ id = "ZUG" }], [{ id = "RDG" }]]
runway_filter = [[]]

[EDMMWLD]
description = "Walda"
volumes = ["EDMMWLD_105_245", "EDMMWLD_245_315"]
position_priority = [[{ id = "WLD" }], [{ id = "NDG" }], [{ id = "TRU" }], [{ id = "ZUG" }], [{ id = "RDG" }]]
runway_filter = [[]]

[EDMMFUE]
description = "Füssen"
volumes = ["EDMMFUE_000_105", "EDMMFUE_195_245", "EDMMFUE_105_145", "EDMMFUE_145_195", "EDMMFUE_245_315"]
position_priority = [[{ id = "FUE" }], [{ id = "ZUG" }], [{ id = "TRU" }], [{ id = "RDG" }]]
runway_filter = [[]]

[EDMMSTA]
description = "Starnberg"
volumes = ["EDMMSTA_165_245", "EDMMSTA_000_165", "EDMMSTA_245_315"]
position_priority = [[{ id = "STA" }], [{ id = "TEG" }], [{ id = "TRU" }], [{ id = "ZUG" }], [{ id = "RDG" }]]
runway_filter = [[]]

[EDMMZUG]
description = "Zugspitze"
volumes = ["EDMMZUG_245_315", "EDMMZUG_165_245", "EDMMZUG_000_105", "EDMMZUG_105_165"]
position_priority = [[{ id = "ZUG" }], [{ id = "TRU" }], [{ id = "RDG" }]]
runway_filter = [[]]

[EDMMTEG]
description = "Tegernsee"
volumes = ["EDMMTEG_000_165", "EDMMTEG_165_195", "EDMMTEG_195_245", "EDMMTEG_245_315"]
position_priority = [[{ id = "TEG" }], [{ id = "TRU" }], [{ id = "ZUG" }], [{ id = "RDG" }]]
runway_filter = [[]]

[EDMMTRU]
description = "Traun"
volumes = ["EDMMTRU_000_125", "EDMMTRU_195_245", "EDMMTRU_125_195", "EDMMTRU_245_315"]
position_priority = [[{ id = "TRU" }], [{ id = "NDG" }], [{ id = "TEG" }], [{ id = "ZUG" }], [{ id = "RDG" }]]
runway_filter = [[]]

[EDMMCA4]
description = "Freising High/Low"
volumes = ["EDMMTMANH_095_195", "EDMMTMANL_000_095"]
position_priority = [
  [
    { id = "DMNH" },
    { id = "DMNL" },
  ],
  [
    { id = "DMSH" },
    { id = "DMSL" },
  ],
  [
    { id = "DMND" },
  ],
  [
    { id = "DMSD" },
  ],
  [
    { id = "NDG" },
  ],
  [
    { id = "ZUG" },
  ],
  [
    { id = "RDG" },
  ],
]
runway_filter = [[]]

[EDMMTMAS]
description = "Erding High/Low"
volumes = ["EDMMTMASH_095_195", "EDMMTMASL_000_095"]
position_priority = [
  [
    { id = "DMSH" },
    { id = "DMSL" },
  ],
  [
    { id = "DMNH" },
    { id = "DMNL" },
  ],
  [
    { id = "DMSD" },
  ],
  [
    { id = "DMND" },
  ],
  [
    { id = "NDG" },
  ],
  [
    { id = "ZUG" },
  ],
  [
    { id = "RDG" },
  ],
]
runway_filter = [[]]

[EDMMILR]
description = "Iller"
volumes = ["EDMMILR2_095_105", "EDMMILR1_000_105"]
position_priority = [
  [
    { id = "ILR" },
  ],
  [
    { id = "SWA" },
  ],
  [
    { id = "FUE" },
  ],
  [
    { id = "ZUG" },
  ],
  [
    { id = "TRU" },
  ],
  [
    { id = "RDG" },
  ],
]
runway_filter = [[]]

[EDMMSWA1]
description = ""
volumes = ["EDMMNDG_000_105"]
position_priority = [
  [
    { id = "SWA" },
  ],
  [
    { id = "NDG" },
  ],
  [
    { id = "TRU" },
  ],
  [
    { id = "WLD" },
  ],
  [
    { id = "ZUG" },
  ],
  [
    { id = "RDG" },
  ],
]
runway_filter = [[]]

[EDMMSWA2]
description = ""
volumes = ["EDMMWLD_000_105"]
position_priority = [
  [
    { id = "SWA" },
  ],
  [
    { id = "WLD" },
  ],
  [
    { id = "NDG" },
  ],
  [
    { id = "TRU" },
  ],
  [
    { id = "ZUG" },
  ],
  [
    { id = "RDG" },
  ],
]
runway_filter = [[]]

[EDMMSWA3]
description = ""
volumes = ["EDMMALB_000_105"]
position_priority = [
  [
    { id = "SWA" },
  ],
  [
    { id = "ALB" },
  ],
  [
    { id = "WLD" },
  ],
  [
    { id = "RDG" },
  ],
  [
    { id = "EGG" },
  ],
  [
    { id = "ZUG" },
  ],
]
runway_filter = [[]]
