[EDUUCHI]
description = ""
volumes = ["EDUUCHI24_355_365", "EDUUCHI141_315_355", "EDUUCHI34_365_375", "EDUUCHI44_375_660"]
position_priority = [
  [
    { id = "CHI" },
  ],
  [
    { id = "ISA" },
  ],
  [
    { id = "ALP" },
  ],
  [
    { id = "DON" },
  ],
  [
    { id = "ERL" },
  ],
  [
    { fir = "EDMM", id = "TRU" },
  ],
  [
    { fir = "EDMM", id = "NDG" },
  ],
  [
    { fir = "EDMM", id = "TEG" },
  ],
  [
    { fir = "EDMM", id = "ZUG" },
  ],
  [
    { fir = "EDMM", id = "RDG" },
  ],
]
runway_filter = [[]]

[EDUUSAL]
description = ""
volumes = ["EDUUSAL22_365_660", "EDUUSAL12_315_365"]
position_priority = [
  [
    { id = "SAL" },
  ],
  [
    { id = "SPE" },
  ],
  [
    { id = "HVL" },
  ],
  [
    { id = "ERL" },
  ],
  [
    { fir = "EDMM", id = "GER" },
  ],
  [
    { fir = "EDMM", id = "HAL" },
  ],
  [
    { fir = "EDMM", id = "MEI" },
  ],
  [
    { fir = "EDMM", id = "HOF" },
  ],
]
runway_filter = [[]]

[EDUUERL]
description = ""
volumes = ["EDUUERL22_365_660", "EDUUERL12_315_365"]
position_priority = [
  [
    { id = "ERL" },
  ],
  [
    { id = "DON" },
  ],
  [
    { id = "SAL" },
  ],
  [
    { fir = "EDMM", id = "BBG" },
  ],
  [
    { fir = "EDMM", id = "HOF" },
  ],
  [
    { fir = "EDMM", id = "RDG" },
  ],
]
runway_filter = [[]]

[EDUUISA]
description = ""
volumes = ["EDUUISA34_365_375", "EDUUISA14_315_355", "EDUUISA44_375_660", "EDUUISA24_355_365"]
position_priority = [
  [
    { id = "ISA" },
  ],
  [
    { id = "CHI" },
  ],
  [
    { id = "ALP" },
  ],
  [
    { id = "DON" },
  ],
  [
    { id = "ERL" },
  ],
  [
    { fir = "EDMM", id = "NDG" },
  ],
  [
    { fir = "EDMM", id = "WLD" },
  ],
  [
    { fir = "EDMM", id = "TRU" },
  ],
  [
    { fir = "EDMM", id = "ZUG" },
  ],
  [
    { fir = "EDMM", id = "RDG" },
  ],
]
runway_filter = [[]]

[EDUUALP]
description = ""
volumes = ["EDUUALP14_315_355", "EDUUALP34_365_375", "EDUUALP44_375_660", "EDUUALP24_355_365"]
position_priority = [
  [
    { id = "ALP" },
  ],
  [
    { id = "ISA" },
  ],
  [
    { id = "DON" },
  ],
  [
    { id = "ERL" },
  ],
  [
    { fir = "EDMM", id = "ZUG" },
  ],
  [
    { fir = "EDMM", id = "TRU" },
  ],
  [
    { fir = "EDMM", id = "RDG" },
  ],
]
runway_filter = [[]]

[EDUUSPE]
description = ""
volumes = ["EDUUSPE12_315_365", "EDUUSPE22_365_660"]
position_priority = [
  [
    { id = "SPE" },
  ],
  [
    { id = "SAL" },
  ],
  [
    { id = "HVL" },
  ],
  [
    { id = "ERL" },
  ],
  [
    { fir = "EDMM", id = "MEI" },
  ],
  [
    { fir = "EDMM", id = "GER" },
  ],
  [
    { fir = "EDMM", id = "HAL" },
  ],
  [
    { fir = "EDMM", id = "HOF" },
  ],
]
runway_filter = [[]]

[EDUUDON]
description = ""
volumes = ["EDUUDON34_365_375", "EDUUDON44_375_660", "EDUUDON24_355_365", "EDUUDON14_315_355"]
position_priority = [
  [
    { id = "DON" },
  ],
  [
    { id = "ALP" },
  ],
  [
    { id = "ERL" },
  ],
  [
    { fir = "EDMM", id = "RDG" },
  ],
  [
    { fir = "EDMM", id = "EGG" },
  ],
  [
    { fir = "EDMM", id = "ALB" },
  ],
  [
    { fir = "EDMM", id = "WLD" },
  ],
  [
    { fir = "EDMM", id = "ZUG" },
  ],
]
runway_filter = [[]]
